version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: midd-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - midd-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: midd-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - midd-network

  db:
    image: postgres:15
    container_name: midd-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: midd
      POSTGRES_USER: midd
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - midd-network

  redis:
    image: redis:7-alpine
    container_name: midd-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - midd-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: midd-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - midd-network

networks:
  midd-network:
    driver: bridge

volumes:
  dbdata:
    driver: local